import createMiddleware from "next-intl/middleware";
import {routing} from "./i18n/routing";

export default createMiddleware(routing);

export const config = {
  // Match all pathnames except API, _next, _vercel internals, and files with
  // an extension (e.g. favicon.ico, /icons/*.svg). The middleware itself
  // resolves which paths actually require locale handling, so adding a new
  // locale to i18n/routing.ts is sufficient — no matcher edits needed.
  // Exclude:
  //  - api / _next / _vercel internals
  //  - paths with a file extension (favicon.ico, sitemap.xml, etc.)
  //  - root metadata-file routes generated by Next.js (icon, apple-icon,
  //    opengraph-image, twitter-image, manifest) — these live at the app
  //    root, not under [locale], so they must not be locale-redirected.
  matcher: ["/((?!api|_next|_vercel|icon|apple-icon|opengraph-image|twitter-image|manifest|.*\\..*).*)"]
};
