import "./globals.css";
import type {Metadata, Viewport} from "next";
import {Fraunces, Inter} from "next/font/google";
import Script from "next/script";
import type {ReactNode} from "react";
import {Analytics} from "@vercel/analytics/next";
import {SpeedInsights} from "@vercel/speed-insights/next";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap"
});

const fraunces = Fraunces({
  subsets: ["latin"],
  variable: "--font-display",
  weight: ["600", "700", "800"],
  display: "swap"
});

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL ?? "https://immigrantmoney.us"),
  title: {
    default: "ImmigrantMoney",
    template: "%s | ImmigrantMoney"
  },
  description: "Free bilingual financial tools for immigrants in the United States.",
  robots: {
    index: true,
    follow: true
  },
  // Multi-format favicon coverage:
  //   - SVG (modern browsers incl. Safari 17+): scales crisply, brand-true
  //   - PNG 32×32 (legacy fallback, generated by app/icon0.tsx via next/og)
  //   - Apple touch icon 180×180 (iOS home screen, app/apple-icon.tsx)
  //   - Safari pinned-tab mask-icon (monochrome SVG, tinted brand blue)
  // Setting `icons` here overrides Next.js' auto-injection from the metadata
  // file convention, so we declare every variant explicitly.
  icons: {
    icon: [
      {url: "/icon.svg", type: "image/svg+xml"},
      {url: "/icon0", type: "image/png", sizes: "32x32"}
    ],
    shortcut: [{url: "/icon.svg"}],
    apple: [{url: "/apple-icon", sizes: "180x180", type: "image/png"}],
    other: [{rel: "mask-icon", url: "/safari-pinned-tab.svg", color: "#1D4ED8"}]
  }
};

export const viewport: Viewport = {
  themeColor: "#1D4ED8"
};

export default function RootLayout({children}: {children: ReactNode}) {
  // AdSense client is the publisher ID (ca-pub-...). Setting it loads the
  // adsbygoogle.js script — needed for AdSense to verify ownership during
  // application review, and to serve ads once the site is approved.
  const adsenseClient = process.env.NEXT_PUBLIC_ADSENSE_CLIENT;

  return (
    <html lang="en" className={`${inter.variable} ${fraunces.variable}`}>
      <body className="font-sans antialiased">
        {children}
        <Analytics />
        <SpeedInsights />
        {adsenseClient ? (
          <Script
            async
            crossOrigin="anonymous"
            id="adsense-script"
            src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${adsenseClient}`}
            strategy="afterInteractive"
          />
        ) : null}
      </body>
    </html>
  );
}
